void lcdprint(int x,int y,char* str);
void lcdclr(int x,int y,unsigned int num);
void timerns();
void readkey();
void getangle();
void angle_judgement();
void pwm_adjustment();
void print_inf();
void angle_sumup();
void angle_inited();
